### ISSUE TITLE
Typo when writing a report configuration plan

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/QualificationRunner#10]
"ObservededDataSets" instead of "ObservedDataSets"
(s. https://github.com/Open-Systems-Pharmacology/QualificationPlan/blob/d6101524df0e856361295a4ad3a46a6a6ca7323e/examples/minimal/reporting%20engine%20input/report-configuration-plan.json#L19)

**Comment by msevestre** [comment]
interesting
