### ISSUE TITLE
Export only simulations used in the plots to pkml

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/QualificationRunner#105]
If a project is referenced by a qualification plan: not necessarily all simulations from this project are used in the plots.
In the extrem case: not a single simulation from the project is used for plots (e.g. when the project is used only for the building block inheritance).

At the moment, all simulation from all projects are exported to pkml, which might take quite a while.
(e.g. for the CYP3A4-DDI qualification plan 507 simulations are exported to pkml, but only 224 simulations are used for plots)

It would be better if only simulations effectively used by plots are exported to pkml.
For this, all {project, simulation} combinations used under the Plots node of a qualification plan must be determined.

Option 1: all {project, simulation} combinations are identified by the QualificationRunner
Option 2: QualificationRunner becomes an optional argument: file name, where all used {project, simulation} pairs are stored. When called by the Reporting Engine: RE analyzes the qualification plan first and generates such a file, then calls the QualificationRunner passing generated file as argument

**Comment by msevestre** [comment]
Starting now
