### ISSUE TITLE
Indentation changed?

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/QualificationRunner#116]
Compare [V10 (left)](https://github.com/Open-Systems-Pharmacology/OSP-PBPK-Model-Library/blob/master/Alprazolam/Alprazolam_evaluation_report.md#31-final-input-parameters) vs. [V11 (right)](https://github.com/Yuri05/OSP-PBPK-Model-Library/blob/OSP11_137_128/Alprazolam/Alprazolam_evaluation_report.md#31-final-input-parameters):
<img width="400" src="https://user-images.githubusercontent.com/25061876/166800312-3642183f-5873-4699-a58e-60431ae1b0d3.png">  <img width="400" src="https://user-images.githubusercontent.com/25061876/166800347-cf577cd7-72f6-455b-9862-9c1f419e40a5.png">

When recreating the reports with V11 (Matlab-RE) - comparison shows that the indentaion of the Input-BBs in V11 was decreased by 1:
![grafik](https://user-images.githubusercontent.com/25061876/166801016-d4af2c9c-d12f-4b8f-9e83-3351a9a3958a.png)

On purpose? 
In V10 the indentation was correct (e.g. for a section of level 2 "Compound" was Header 3).
Now in V11 is not correct anymore ("Compound starts on the level 2 as well etc.)

**Comment by msevestre** [comment]
@Yuri05 I just saw this one. This is probably a bug in PK-Sim...which I just released. What do we do here?

**Comment by msevestre** [comment]
Correction. This is estimated in the QualificatonRunner `getSectionLevel`
I do not see anything wrong here..

**Comment by msevestre** [comment]
@Yuri05 Was it adjusted by hand? I don't see any differences

**Comment by msevestre** [comment]
this line is probablu wrong
 var section = sections.FirstOrDefault(x => x.Id == sectionId || x.Reference == sectionReference);


If both are null, this will probably return the section where it should return false. This needs to be changed

**Comment by Yuri05** [comment]
>Was it adjusted by hand? I don't see any differences

Yes. I just shifted all input subchapters by 1 level :)
If it is in the QualiRunner - would be good to fix it now.
