### ISSUE TITLE
Qualification runner errror creating pk-ratio plots when having more than 1 unit in observed data

### ISSUE THREAD

**Issue by Incei** [Open-Systems-Pharmacology/QualificationRunner#126]
Qualification runner errror creating pk-ratio plots when having more than 1 unit in observed data, below the datafile and the qualification package that fails to create pk-ratio plots due to having 2 units....

[Pediatrics.csv](https://github.com/Open-Systems-Pharmacology/QualificationRunner/files/10731257/Pediatrics.csv)

https://github.com/Incei/Pediatric_Qualification_Package_P-gp_Ontogeny/tree/Version_2

**Comment by Incei** [comment]
I have tried converting all observed CL values to 1 unit and run it, it only works when adjusted the units to ml/min/kg, when using ml/min unit it still doesn't work.

**Comment by Yuri05** [comment]
Yes, CL units can be accepted currently only per BodyWeight and must be given in one of the units
https://github.com/Open-Systems-Pharmacology/OSPSuite.Dimensions/blob/a31290e1a6d49c1f874762e7fec8c909bc230062/OSPSuite.Dimensions.xml#L390-L398
