### ISSUE TITLE
Content file not copied

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/QualificationRunner#34]
[input.zip](https://github.com/Open-Systems-Pharmacology/QualificationRunner/files/3163080/input.zip)

Qualification plan refers to `content.md` in the same folder. When processed with the qualification runner, it's not copied to the target folder.

`QualificationRunner -i C:\input\Aciclovir_Qualiplan.json -o C:\re_input -l C:\re_input\logfile.txt -p C:\PKSim7.5`

Input folder:
![grafik](https://user-images.githubusercontent.com/25061876/57469986-1c741880-7288-11e9-8c8a-b0f5ab51686b.png)

Output folder after QualiRunner is finished:
![grafik](https://user-images.githubusercontent.com/25061876/57470013-2f86e880-7288-11e9-9fc0-c80289b472b4.png)

**Comment by msevestre** [comment]
This is not according to specs. Content should be defined in a `Content` Folder. The whole folder will be copied as is without any further processing from the tool.

see https://github.com/Open-Systems-Pharmacology/QualificationRunner/blob/develop/src/QualificationRunner.Core/Services/QualificationRunner.cs#L121

**Comment by msevestre** [comment]
Closing. Please reopen if you want to change. But this would mean we need to analyze the sections
