### ISSUE TITLE
Qualification runner does not copy "Content" to specified reporting engine input folder

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/QualificationRunner#35]
The sections mentioned in the qualification plan are not copied to the reporting engine input folder.

e.g:
"Sections": [
    {
      "Id": 1,
      "Title": "Chapter 1",
      "Content": "Content/Section1.md"
    }
  ],

**Comment by msevestre** [comment]
Please attach the qualification plan as well as the folder structure. This is exactly how all other examples are setup so I don't know why this one would be different

it is crucial to have the content in a `Content` folder (see #34 )

**Comment by sfrechen** [comment]
Please see here:

https://github.com/sfrechen/Qualification-DDI-CYP3A4

**Comment by msevestre** [comment]
ok thanks. Going to check it out right now :)

**Comment by msevestre** [comment]
I can reproduce. Thanks

**Comment by sfrechen** [comment]
It would be helpful to allow also referencing to an url of certain sections, e.g.:

**"Sections": [
    {
      "Id": 1,
      "Title": "Chapter 1",
      "Content": "https://raw.githubusercontent.com/Open-Systems-Pharmacology/Itraconazole-Model/master/README.md"
    }
  ],**

Is that possible?

**Comment by msevestre** [comment]
see issue https://github.com/Open-Systems-Pharmacology/QualificationRunner/issues/38
