### ISSUE TITLE
Referencing remote content in Section

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/QualificationRunner#38]
It would be helpful to allow also referencing to an url of certain sections, e.g.:

**"Sections": [
    {
      "Id": 1,
      "Title": "Chapter 1",
      "Content": "https://raw.githubusercontent.com/Open-Systems-Pharmacology/Itraconazole-Model/master/README.md"
    }
  ],**

Is that possible?

/cc @sfrechen

**Comment by msevestre** [comment]
@sfrechen It is possible but would require some implementation. At the moment, the `QualificationRunner` just forwards the section to the reporting engine.

If we want to implement this logic, the `Content` folder would not be required anymore. Instead the `QualificationRunner` would gather all content files (local and global) and copy them into a Content folder to be processed by the ReportingEngine

Is this `must` or `nice to have`? Probably 1/2 day of work

**Comment by sfrechen** [comment]
To avoid redundancy, it is rather a "must". We already notice that many qualification plans share certain sections.
Copying from different locations would be sufficient.

**Comment by msevestre** [comment]
Copying from local vs remote is not what makes it harder. We have to implement a parsing of the sections (tree), edit each entry to reflect the copied file etc...
