### ISSUE TITLE
Images in remote content

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/QualificationRunner#40]
If a remote content file contains a reference to an image - what will happen to this image in the final report?

1. If an image is referenced by the **full url** - it might work already now. Depends on the behaviour of Markdown-Joiner - to be checked.
2. If an image is referenced by the **relative path** - it will not work without explicit downloading the image to the local system.

**Comment by msevestre** [comment]
Adding image to content would have worked with the previous implementation (at least with local images) because we were copying the whole folder.

I don't think it will work in either scenario now and I don't think there is anything we can do about it

**Comment by Yuri05** [comment]
Should we still copy the Content folder first?

**Comment by msevestre** [comment]
this is obsolete now that we use another tool to generate pdf
