### ISSUE TITLE
No error message if output folder not empty

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/QualificationRunner#45]
If the output folder is not empty and QualiRunner was called without `-force` - it exits without error message.

In the log file the error message below appears
`Error: Output folder is not empty. Please use -f to force deletion. Beware: All files in the output folder will be deleted!`

The same error message should be shown in the console

**Comment by msevestre** [comment]
Please try again and see if this is fixed with #44 
The issue was that we would close the program without letting the time for the console to flush because of #36

**Comment by Yuri05** [comment]
yes, fixed with that.
