### ISSUE TITLE
Problem downloading very small files

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/QualificationRunner#47]
It seems to be an issue that very small files (e.g. markdown with only few lines of text) cannot be properly handled by runner.

E.g. in [this quali plan](https://github.com/sfrechen/Qualification-DDI-CYP3A4/blob/master/input/master_quali_plan.json) the  file **https://raw.githubusercontent.com/Open-Systems-Pharmacology/Qualification-text-modules/master/Intro_Model_evaluation_GOF.md** is used. 

https://github.com/sfrechen/Qualification-DDI-CYP3A4/blob/8fab373db75af7d9c901e6e87ae34d72c88787f5/input/master_quali_plan.json#L4833-L4835

File exists and contains one text line.

When processing the plan: errors below appear
```
dbug: Qualification Runner[0]
      Content file downloaded from https://raw.githubusercontent.com/Open-Systems-Pharmacology/Qualification-text-modules/master/Intro_Model_evaluation_GOF.mdto C:\2del\QualiExample01\re_input\temp\_content\Intro_Model_evaluation_GOF.md
fail: Qualification Runner[0]
      content file 'https://raw.githubusercontent.com/Open-Systems-Pharmacology/Qualification-text-modules/master/Intro_Input_parameters.md' does not exist.
fail: Qualification Runner[0]
      Qualification Workflow failed
```

**Comment by msevestre** [comment]
@Yuri05 wow. No idea how to go about this. It's also very hard to reproduce (e.g. I can't)

**Comment by Yuri05** [comment]
ok, the quali plan changed in the mean time to avoid those issues.
Attached is the plan where the issue occurred:
[master_quali_plan.zip](https://github.com/Open-Systems-Pharmacology/QualificationRunner/files/3212273/master_quali_plan.zip)

**Comment by sfrechen** [comment]
Though we have a work around currently, we should still put some focus here!
Agree wit Yuri05 that the qualification runner fails if small files are included.

**Comment by msevestre** [comment]
Going to look into that now. Very hard since I cannot reproduce

**Comment by msevestre** [comment]
Ok this is because we keep downloading the same file over and over again in //. I am going to disable // download for now and see if this helps
