### ISSUE TITLE
Allow to reference protein expression profiles from remote individuals

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/QualificationRunner#57]
Similar as simulation parameters can be referenced, it would be useful to allow for an individual to inherit the complete expression profile from a remote individual (keeping its anthropometric data).

![image](https://user-images.githubusercontent.com/26569320/74924917-9d457080-53d3-11ea-9804-5dc3318054ad.png)

This protein expression should inherit the **"Molecules"** block of a snaphot of an individual.

@Yuri05

**Comment by msevestre** [comment]
see https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1847

**Comment by Yuri05** [comment]
fixed with "Expression profiel as standalone BB"
