### ISSUE TITLE
Version 9 cannot find PK-Sim

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/QualificationRunner#63]
WIth the nightly build (9.0.67) I get an error

```
fail: Qualification Runner[0] 
      PKSim.CLI.exe installation folder was not found. Ensure that PK-Sim was installed with the setup OR specify the --pksim option 
```

I have PK-Sim 8 installed and PK-Sim nightly as a portable. Do I need PK-Sim 9 installed for the ver.9 of the quilification runner?

I also tried to specify the path to PK-Sim 9 by

`startQualificationRunner(qualificationRunnerFolder, qualificationPlan, REInput_path, '--pksim', '"c:\Program Files\Open Systems Pharmacology\PK-Sim 9.0\"');`

But then I get the error 

fail: Qualification Runner[0] 
      Illegales Zeichen im Pfad. 
       
      Stack trace: 
      bei System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional) 
         bei System.IO.Path.Combine(String path1, String path2) 
         bei QualificationRunner.Core.QualificationRunnerConfiguration.getPKSimCLIPathFor(String pksimInstallationFolder) 
         bei QualificationRunner.Core.QualificationRunnerConfiguration.PKSimCLIPathFor(String pksimInstallationFolder) 
         bei QualificationRunner.Core.Services.QualificationEngine.<execute>d__8.MoveNext() 
      --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde --- 
         bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
         bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
         bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() 
         bei QualificationRunner.Core.Services.QualificationRunner.<RunBatchAsync>d__5.MoveNext() 
       --- End of inner exception stack trace --- 
         bei System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) 
         bei System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken) 
         bei System.Threading.Tasks.Task.Wait() 
         bei QualificationRunner.Program.startCommand[TRunOptions](CLICommand`1 command) 
fail: Qualification Runner[0] 
      Qualification Workflow failed

**Comment by msevestre** [comment]
```
startQualificationRunner(qualificationRunnerFolder, qualificationsPlan, REInput_path, '--pksim', '"c:\Program Files\Open Systems Pharmacology\PK-Sim 9.0\"')
```

what is this?

>I have PK-Sim 8 installed and PK-Sim nightly as a portable. Do I need PK-Sim 9 installed for the ver.9 of the quilification runner? 

Yes

>the --pksim option

THis needs to be pass as an argument to the runner. 

something like QualitifcationRunner.exe --pksim 
see QualitifcationRunner.exe --help for details

**Comment by Yuri05** [comment]
ok, the problem is that `-p` (or `--pksim`) option cannot handle path in double quotes.
Thus something like `QualificationRunner ... -p "PathToPkSim"` fails, 
but `QualificationRunner ... -p PathToPkSim` works (if PathToPkSim does not contain spaces).

@PavelBal So workaround is: save PK-Sim 9 in a folder without spaces and remove double quotes in the call.

**Comment by Yuri05** [comment]
>what is this?

This is [this](https://github.com/Open-Systems-Pharmacology/Reporting-Engine/blob/develop/src/code/qualification/auxiliaries/startQualificationRunner.m) 😄

**Comment by msevestre** [comment]
ok. I am trying to never touch this matlab stuff ...like never ever

**Comment by Yuri05** [comment]
yep.. but this is the bug in the QualiRunner indeed. Matlab just calls it with passed arguments.

**Comment by msevestre** [comment]
But why do you pass " and '? this looks weird to me. .net supports path with path without problems when using a CLI

**Comment by Yuri05** [comment]
simple quotes are matlab string, double quotes are passed to the runner then.
So the Runner is called like this: `QualiRunner ... --pksim "c:\Program Files\Open Systems Pharmacology\PK-Sim 9.0\"` 
And the problem are **double quotes** in the path following `--pksim`.
(Probably the Runner does not remove them before appending PK-Sim.exe so that the path becomes something like `"c:\Program Files\Open Systems Pharmacology\PK-Sim 9.0\"PK-Sim.exe`)

**Comment by PavelBal** [comment]
Guys, you made my day :D 

Yes, copying PK-Sim to a path without spaces works. Thank you @Yuri05 !

**Comment by PavelBal** [comment]
Obsolete.
