### ISSUE TITLE
Map multiple data to one model output

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/QualificationRunner#64]
Maybe it's already there and I missed it - it would be great to map multiple observed data entries to a model output in one OutputMappings-entry. Right now I write:

```
 "OutputMappings": [
                            {
                                "Project": "ProjectName",
                                "Simulation": "Simulation 1",
                                "Output": "Organism|PeripheralVenousBlood|Compound|Plasma (Peripheral Venous Blood)",
                                "ObservedData": "ObsData_ind1",
                                "Color": "#2166ac"
                            },
                            {
                                "Project": "ProjectName",
                                "Simulation": "Simulation 1",
                                "Output": "Organism|PeripheralVenousBlood|Compound|Plasma (Peripheral Venous Blood)",
                                "ObservedData": "ObsData_ind2",
                                "Color": "#2166ac"
                            },
```

Instead, I would like to be able to do

```
 "OutputMappings": [
                            {
                                "Project": "ProjectName",
                                "Simulation": "Simulation 1",
                                "Output": "Organism|PeripheralVenousBlood|Compound|Plasma (Peripheral Venous Blood)",
                                "ObservedData": "ObsData_ind1",
                                "ObservedData": "ObsData_ind2",
                                "Color": "#2166ac"
                            }
```

**Comment by msevestre** [comment]
This is not a valid json syntax (two properties with the same name)
However one could think about something like 

```
 "OutputMappings": [
                            {
                                "Project": "ProjectName",
                                "Simulation": "Simulation 1",
                                "Output": "Organism|PeripheralVenousBlood|Compound|Plasma (Peripheral Venous Blood)",
                                "ObservedDataList": ["ObsData_ind1", "ObsData_ind2"]
                                "Color": "#2166ac"
                            }
```

**Comment by PavelBal** [comment]
Yes, would be great. Would make the life much easier when having individual data.

**Comment by Yuri05** [comment]
Is Reporting Engine, not Quali Runner

**Comment by msevestre** [comment]
? There is no such json in the reporting engine right?

At least not written by hand?

**Comment by Yuri05** [comment]
It's in qualification plans, e,g. https://github.com/Open-Systems-Pharmacology/Pediatric_Qualification_Package_GFR_Ontogeny/blob/4e905c62f348a107e3cb96b7fe44c5f8e201da75/input/Qualification-Ontogeny-Distribution-GFR.json#L955

So what @PavelBal would like to have is indeed something like you proposed in https://github.com/Open-Systems-Pharmacology/QualificationRunner/issues/64#issuecomment-629341381

But that's part of "non-PKSim" plots, which is just copied by QualiRunner 1:1 into Report-Configuration-Plans.

**Comment by msevestre** [comment]
yeah agreed.
That's why it should be easier to create for the user. Now I understand that the reporting engine will need to understand this. But we need to adapt the schema here as well correct?
