### ISSUE TITLE
Imported observers not supported?

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/QualificationRunner#65]
I have created an observer and loaded it in PK-Sim. I then try to map the output of this observer to data in the qualification plan (let's say the observer is called `Observer Plasma (Peripheral Venous Blood)`):

```
                            {
                                "Project": "MyProject",
                                "Simulation": "mySim",
                                "Output": "Organism|PeripheralVenousBlood|Compoound|Observer Plasma (Peripheral Venous Blood)",
                                "ObservedData": "SomeDatta",
                                "Color": "#b2182b"
                            },
```

I get warnings:

```
warn: MyProject[0] 
      Could not find quantity with path 'mySim|Organism|PeripheralVenousBlood|Compoound|Observer Plasma (Peripheral Venous Blood)'. 
``` 

Exporting the corresponding simulation to PKML and trying the access the observer from R works (I copy-pasted the path from the error message too make sure there is no typo).

**Comment by msevestre** [comment]
Observers are not supported in snapshot yet. Therefore they will not be in the project created from snapshot

**Comment by msevestre** [comment]
see https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1359

**Comment by msevestre** [comment]
This is indeed an issue :)

**Comment by msevestre** [comment]
FYI: I'll probably have a fix for this by Friday

**Comment by Yuri05** [comment]
should be fixed with https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1359
