### ISSUE TITLE
Nightly builds created daily even if there were no changes

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/QualificationRunner#66]
![grafik](https://user-images.githubusercontent.com/25061876/82735029-f5677800-9d1e-11ea-9f37-af0584cd2cef.png)

**Comment by msevestre** [comment]
It's the behavior of appveyor
Either on change or on schedule
Nightly are on schedule, other are nightly

**Comment by msevestre** [comment]
It's the same for PKsim , Mobi etc.. nothign we can do here
