### ISSUE TITLE
Add option to NOT calculate the outputs in PKSim

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/QualificationRunner#82]

**Comment by msevestre** [comment]
This is now the default of the qualification runner... @Yuri05 Should this version for v10 calculate by default ?Probably yes

**Comment by Yuri05** [comment]
>Should this version for v10 calculate by default ?Probably yes

Yes! Otherwise we would need to adjust all the (matlab) workflow start script for the current qualification reports

**Comment by msevestre** [comment]
This if fixeds in #85
