### ISSUE TITLE
No PKMLs generated by QualificationRunner for this qualification report

### ISSUE THREAD

**Issue by abdullahhamadeh** [Open-Systems-Pharmacology/QualificationRunner#89]
Only XML files are generated in the reporting engine input folder

**Comment by Yuri05** [comment]
moving the issue to the QualiRunner-Repo

**Comment by msevestre** [comment]
Can you show me how you are calling the runnner? And which files are you using? I need to be able to reproduce

**Comment by abdullahhamadeh** [comment]
`'C:/path/to/QualificationRunner 10.0.40/QualificationRunner.exe' -i 'C:/path/to/Qualification-DDI-CYP2C19-main/Qualification/Input/qualification_plan.json' -o 'C:/path/to/reporting engine input/' -p 'C:/Program Files/Open Systems Pharmacology/PK-Sim 9.1/'`

**Comment by msevestre** [comment]
ok you are mixing v9 of PKSim and v10 of runner. Please install the latest portable version of PKSim and try again 

https://ci.appveyor.com/project/open-systems-pharmacology-ci/pk-sim/build/artifacts

**Comment by msevestre** [comment]
using v10 of pksim I am getting what we expect
![image](https://user-images.githubusercontent.com/1041237/133828409-08afd5a5-8ea6-43fa-91be-fcd2af05d1e7.png)

@Yuri05 For the moment, PKSim is still running the simulation. I am going to make it optional (default true) so that we can turn that off (compatible with current Matlab reporting engine). Then when we have completely migrated to R, we can set the default to true?

Or is it ok to set the default to run = FALSE (and then we can just update the call in the matlarb reporting engine). I would prefer this solution. Let me know

**Comment by abdullahhamadeh** [comment]
@msevestre can you pls point me to v10 of pksim?  I see only v9.1 [here](https://github.com/Open-Systems-Pharmacology/PK-Sim/releases/tag/v9.1)

**Comment by msevestre** [comment]
https://github.com/Open-Systems-Pharmacology/QualificationRunner/issues/89#issuecomment-921908695

**Comment by abdullahhamadeh** [comment]
oops, I need better glasses

**Comment by msevestre** [comment]
maybe you just need glasses :)

**Comment by msevestre** [comment]
beware. At the moment, it is also calculating the simulation which is not what you want. I am adding an option to the runner to turn that off. So once you are done with generating the pkml etc.. you should deleted all csv results files

**Comment by Yuri05** [comment]
> I am going to make it optional (default true) so that we can turn that off (compatible with current Matlab reporting engine). Then when we have completely migrated to R, we can set the default to true?

Would prefer this option for now. No need for the new version of Matlab-RE then and no unexpected side effects due to the change of the default :)

**Comment by msevestre** [comment]
see PR. Not possible with flag. So we need to update the code in reporting engine and add the -r flag

**Comment by Yuri05** [comment]
[V10 TODO list](https://github.com/Open-Systems-Pharmacology/Suite/issues/85) grows...

**Comment by msevestre** [comment]
LEt me see if I can declare the flag as nullable to catch when it's not set...and then say it's true

**Comment by msevestre** [comment]
ok I can't. But I'll create another termp flag "noRun" which by default will be false. Setting --norun will switch it to true

**Comment by msevestre** [comment]
All right. There is the flag --norun that will make sure we do not run the simulation. I am going to add it to the call in the new reporting engine
