### ISSUE TITLE
Logging does not respect logLevel!

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/QualificationRunner#92]
Using loglevel debug is ignored it seems

I am only getting info or error even though I want debug in my call
2021-09-17T13:03:43.8950967-04:00  [INF] Starting qualification workflow (0a76265a)
2021-09-17T13:03:45.1330319-04:00  [INF] Starting validation runs... (9ada36c2)
2021-09-17T13:03:55.9006814-04:00  [INF] Starting qualification runs... (fd6e37cc)
2021-09-17T13:38:00.3478653-04:00  [INF] Starting qualification workflow (0a76265a)
2021-09-17T13:38:03.3288982-04:00  [INF] Starting validation runs... (9ada36c2)
2021-09-17T13:38:15.7447751-04:00  [INF] Starting qualification runs... (fd6e37cc)

here is the call
```
QualificationRunner.exe -i "C:\projects\Qualification-DDI-CYP2C19\Qualification\Input\qualification_plan.json" -o "C:\projects\Qualification-DDI-CYP2C19\Qualification\Output" -p "C:\projects\PK-Sim\src\PKSim\bin\Debug\net472" -l "C:\projects\Qualification-DDI-CYP2C19\Qualification\log.txt" --logLevel Debug -f
```

and yes, I am logging debug ingo
This is also blocking for v10
@PavelBal @Yuri05

**Comment by msevestre** [comment]
Here is how it's initialized in PKSim.CLI

![image](https://user-images.githubusercontent.com/1041237/133832848-dfd2e6ef-8018-4ab4-8af2-9436ff446a9d.png)

and here
![image](https://user-images.githubusercontent.com/1041237/133832880-d0b885f8-4f1f-46da-98f3-71c0bc6b106d.png)

LogLevel debug, name of file log.txt

but the serilog is initialized with info
![image](https://user-images.githubusercontent.com/1041237/133833179-8ee31a4c-f39a-4cc4-81c0-61df035f15d4.png)

and so it the path (somewhere very deep in the hierarchy)
![image](https://user-images.githubusercontent.com/1041237/133833418-e8b335a6-049e-49b3-9464-781bc98732c4.png)

**Comment by msevestre** [comment]
I think that was probably missing in the PKSim init
   if (!string.IsNullOrEmpty(runCommand.LogFileFullPath))
            loggerCreator.AddLoggingBuilderConfiguration(builder =>
               builder
              **    .SetMinimumLevel(runCommand.LogLevel)**
                  .AddFile(runCommand.LogFileFullPath)
            );

Sometimes the file is not created...I am so lost with this serilog package. damm

**Comment by msevestre** [comment]
well even when setting the logleve, it's still does not respect 
![image](https://user-images.githubusercontent.com/1041237/133836173-bc3915fe-45fa-4660-a3af-665214d47954.png)

**Comment by georgeDaskalakis** [comment]
solved in Core, just keeoing this here to update the packages
