### ISSUE TITLE
Simulation outputs not created even if --norun flag was not set

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/QualificationRunner#93]
@msevestre Something is wrong with the flag: when calling the QualiRunner from the Matlab reporting engine: simulation results (csv) are not exported. E.g. when called like below:
`QualificationRunner.exe -i C:\evaluation_plan.json -o C:\re_input -p C:\PK-Sim_10.0.230`
xml and pkml are created, but not CSV with simulation results
![grafik](https://user-images.githubusercontent.com/25061876/133894842-27d5b375-39f5-4501-99ce-58acf0d9d05c.png)

Compare to QualiRunner 9:
![grafik](https://user-images.githubusercontent.com/25061876/133894910-3fc46cf0-5124-4cf8-88ec-2f5bdb3eeec0.png)

**Comment by msevestre** [comment]
Weird..

**Comment by msevestre** [comment]
Just tried locally with the latest version
```
 QualificationRunner.exe -i "C:\projects\Qualification-DDI-CYP2C19\Qualification\Input\qualification_plan.json" -o "C:\test\norun" -p "C:\projects\PK-Sim\src\PKSim\bin\Debug\net472" -l "C:\projects\Qualification-DDI-CYP2C19\Qualification\log.txt" --logLevel Debug -f
info: OSPSuite[0]
      Starting qualification workflow
dbug: OSPSuite[0]
      Arguments:
Log file: C:\projects\Qualification-DDI-CYP2C19\Qualification\log.txt
      Log level: Debug
      Configuration file: C:\projects\Qualification-DDI-CYP2C19\Qualification\Input\qualification_plan.json
      Output folder: C:\test\norun
      Run Simulations: True
```

How does the output look like foe your? do you see the Run Simulations flag?

**Comment by msevestre** [comment]
e.g.  Run Simulations: True or  Run Simulations: False?

**Comment by msevestre** [comment]
as you can see, I have outputs
![image](https://user-images.githubusercontent.com/1041237/133907379-513e3692-e26f-4f1a-bbf7-97d4cf60dfcd.png)

**Comment by msevestre** [comment]
@Yuri05 Can't reproduce. Are you sure you are using the latest version :)

**Comment by Yuri05** [comment]
I'm using QualiRunner 10.0.42
I don't see Run Simulations flag in the output

[log-20210919.txt](https://github.com/Open-Systems-Pharmacology/QualificationRunner/files/7190739/log-20210919.txt)
[Input.zip](https://github.com/Open-Systems-Pharmacology/QualificationRunner/files/7190740/Input.zip)
[QualiRunner_Output.zip](https://github.com/Open-Systems-Pharmacology/QualificationRunner/files/7190741/QualiRunner_Output.zip)

```
QualificationRunner -i C:\Temp\00\Evaluation\Input\evaluation_plan.json -o C:\Temp\00\re_input --logLevel Debug -p C:\PK-Sim_10.0.230 -f -l C:\Temp\00\log.txt
info: OSPSuite[0]
      Starting qualification workflow
dbug: OSPSuite[0]
      Arguments:
Log file: C:\Temp\00\log.txt
      Log level: Debug
      Configuration file: C:\Temp\00\Evaluation\Input\evaluation_plan.json
      Output folder: C:\Temp\00\re_input

dbug: OSPSuite[0]
      Copying static files
info: OSPSuite[0]
      Starting validation runs...
dbug: OSPSuite[0]
      Starting qualification run for project 'Alfentanil'
dbug: OSPSuite[0]
      Qualification configuration for project 'Alfentanil' exported to 'C:\Temp\00\re_input\temp\Alfentanil\config.json'
info: OSPSuite[0]
      Starting qualification runs...
dbug: OSPSuite[0]
      Starting qualification run for project 'Alfentanil'
dbug: OSPSuite[0]
      Qualification configuration for project 'Alfentanil' exported to 'C:\Temp\00\re_input\temp\Alfentanil\config.json'
info: OSPSuite[0]
      Qualification scenario finished in 02m:03s:297ms
info: OSPSuite[0]
      Qualification Workflow finished
```

**Comment by msevestre** [comment]
soemthing is wrong with this version. It is the old one

![image](https://user-images.githubusercontent.com/1041237/134013818-f9766d74-0bfa-4dd3-94af-81de8f3011bd.png)
(still shows the RUN falg as opposed to NO RUN(

**Comment by msevestre** [comment]
yep
![image](https://user-images.githubusercontent.com/1041237/134014369-a3db9d4d-99ff-4e1f-b9b3-c21b3cb85f47.png)

Version 43 as the norun flag. (false by default)
